# Generated by Django 5.0.2 on 2024-02-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creater_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=20)),
                ('project_design', models.TextField()),
                ('end_date', models.DateField()),
                ('tot_pos', models.IntegerField()),
                ('avl_pos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='project_roll_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('roll_name', models.CharField(max_length=20)),
                ('tot_pos', models.IntegerField()),
                ('avl_pos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='project_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('enroller_id', models.IntegerField()),
                ('roll_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='rolls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_name', models.CharField(max_length=20)),
            ],
        ),
    ]
