# Generated by Django 5.0.2 on 2024-03-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_data',
            old_name='project_design',
            new_name='project_descript',
        ),
        migrations.AddField(
            model_name='project_data',
            name='link',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
