# Generated by Django 5.0.2 on 2024-03-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_rolls_roll_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_data',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project_roll_data',
            name='roll_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project_user',
            name='roll_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rolls',
            name='roll_name',
            field=models.CharField(max_length=100),
        ),
    ]
