# Generated by Django 5.0.2 on 2024-03-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_data_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_data',
            name='project_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project_roll_data',
            name='roll_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project_user',
            name='roll_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rolls',
            name='roll_name',
            field=models.CharField(max_length=200),
        ),
    ]
