# Generated by Django 5.0.2 on 2024-02-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=300)),
                ('dept', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
