# Generated by Django 5.0.2 on 2024-02-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
